#!/usr/bin/env zsh
PYPT_ROOT=$HOME/git/python-project-template/{{cookiecutter.repo_name}}
PYPT_COMPONENTS=(release .pypt/commitlog .pypt/ghrel)
PYPT_PROJECTS=("$HOME/git/pkgbuilder")  # fill in your own

for p in $PYPT_PROJECTS; do
    echo "==> $p"
    for c in $PYPT_COMPONENTS; do
        cp -v $PYPT_ROOT/$c $p/$c
    done
done
