#!/bin/bash
# Human-friendly project name.
PROJECT="TEMPLATE"
# Computer-friendly project name, [a-z0-9_\-]
PROJECTLC="tEmplate"

# GitHub username.
GITUSER="Kwpolska"
# Git repository name.  Using $PROJECTLC is recommended.
GITREPO=$PROJECTLC

# Locale type.  One of:
# none      Do not generate nor use any locales.
# gettext   Use GNU gettext (gettext module).
# pyqt4     Use the Qt locale tools (stock Qt + PyQt4).
# pyside    Use the Qt locale tools (stock Qt + PySide).
LOCALETYPE="none"

# Python versions supported.
PYTHON2=1
PYTHON3=1
