#!/usr/bin/zsh
PYPT_ROOT=$HOME/git/python-project-template
PYPT_COMPONENTS=(release .pypt/README.rst .pypt/LICENSE.PyPT .pypt/commitlog .pypt/localegen .pypt/ghrel)
PYPT_PROJECTS=("$HOME/git/pkgbuilder" "$HOME/git/coil")

for p in $PYPT_PROJECTS; do
    for c in $PYPT_COMPONENTS; do
        cp -v $PYPT_ROOT/$c $p/$c
    done
done
