#!/bin/bash
# Human-friendly project name.
PROJECT="Python Project Template"
# Computer-friendly project name, [a-z0-9_\-]
PROJECTLC="tEmplate"

# Locale type.  One of:
# none      Do not generate nor use any locales.
# gettext   Use GNU gettext (gettext module).
# pyqt4     Use the Qt locale tools (stock Qt + PyQt4).
# pyside    Use the Qt locale tools (stock Qt + PySide).
LOCALETYPE="none"
